batch_size: 8
input_cfg:
  array_id: null
  n_subsample: null
  num_arrays: null
  pdb_dir: /ceph/opig-shared/users/haque/DPhil/caliby/cleaned_single_structure_pdb/cryo_H3
  pdb_name_ext: ''
  pdb_name_list: null
model_params_path: model_params
num_samples_per_pdb: 32
num_workers: 8
out_dir: /ceph/opig-shared/users/haque/DPhil/caliby/ensemble_pdbs/cleaned_ensemble_pdbs/cryo_H3
sampling_yaml_path: caliby/configs/protpardelle-1c/multichain_backbone_partial_diffusion.yaml
seed: 0
